# Configs

title: "Ryan Sarau-Young"
name: "Profile for Ryan Sarau-Young"
email: "sarau712@gmail.com"
url: "https://RSa-Young.github.io"
baseurl: "/Ryan-Sarau-Young"
repository: "RSa-Young/Ryan-Sarau-Young"
header:
  image: /assets/images/thumbnail_24-Ryan_Sarau-Young-02.jpg

include:
  - _pages
  - assets
  - index.html
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

# settings for author profile
author:
  name   : "Ryan Sarau-Young"
  avatar : "/assets/images/IMG_1073 (1).jpg
  bio    : "My name is Ryan Sarau-Young, and I am a College Student studying my Bachelor's and Masters simultaneously. I am looking for an internship primarily focusing on data analytics."
  location: "DeKalb, Illinois"
  github : "RSa-Young"
  linkedin: "ryan-sarau-young-057314195"
  email  : "/assets/images/IMG_1073 (1).jpg"


# # comments by disqus
#comments:
  #provider: "disqus"
  #disqus:
    #shortname: "pwills-com"

#analytics:
  #provider: "google"
  #google:
    #tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
